FROM python:3.11
COPY . /services/backend
WORKDIR /services/backend

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload", "--reload-dir", "/services/backend", "--port", "5000"]
